# Generated by Django 5.2 on 2026-04-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
