# Generated by Django 6.0.3 on 2026-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0002_activityregistration_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="participation_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("team", "Team")],
                default="individual",
                max_length=32,
            ),
        ),
    ]
