# Generated by Django 5.2 on 2026-04-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("participant", "0004_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="participation_type",
            field=models.CharField(
                choices=[
                    ("individual", "Individual"),
                    ("team", "Team"),
                    ("audience", "Audience"),
                ],
                default="individual",
                max_length=32,
            ),
        ),
    ]
