# Generated by Django 6.0.3 on 2026-03-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcheck",
            name="payment_proof",
            field=models.FileField(blank=True, null=True, upload_to="payment_proofs/"),
        ),
        migrations.AddField(
            model_name="paymentcheck",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="payment_qrs/"),
        ),
    ]
