# Generated by Django 6.0.3 on 2026-03-29 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("registration_fee", models.CharField(max_length=200)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("is_team_event", models.BooleanField(default=False)),
                ("team_size", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ActivityRegistrationFormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("date", "Date"),
                            ("choice", "Choice"),
                        ],
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=True)),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated options for 'choice' type.",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_fields",
                        to="event.activity",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ActivityRegistrationFormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="registration_uploads/"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_responses",
                        to="event.activity",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.activityregistrationformfield",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=200)),
                ("activity", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tagline", models.CharField(blank=True, max_length=200)),
                ("schedule", models.TextField(blank=True)),
                ("activities_overview", models.TextField(blank=True)),
                ("rules", models.TextField(blank=True)),
                ("date_of_event", models.DateField(blank=True, null=True)),
                ("time_of_event", models.TimeField(blank=True, null=True)),
                ("venue", models.CharField(blank=True, max_length=200)),
                (
                    "location",
                    models.CharField(
                        blank=True, help_text="Map URL or coordinates", max_length=255
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("concert", "Concert"),
                            ("workshop", "Workshop"),
                            ("fest", "Fest"),
                            ("other", "Other"),
                        ],
                        max_length=40,
                    ),
                ),
                ("registration", models.CharField(max_length=200)),
                ("last_registration_date", models.DateField(blank=True, null=True)),
                ("announcement", models.CharField(max_length=200)),
                ("contact_info", models.CharField(blank=True, max_length=200)),
                ("past_event_history", models.TextField(blank=True)),
                (
                    "about_page",
                    models.TextField(blank=True, help_text="Rich text for About page"),
                ),
                (
                    "schedule_page",
                    models.TextField(
                        blank=True, help_text="Rich text for Schedule page"
                    ),
                ),
                (
                    "activities_page",
                    models.TextField(
                        blank=True, help_text="Rich text for Activities page"
                    ),
                ),
                (
                    "contact_page",
                    models.TextField(
                        blank=True, help_text="Rich text for Contact page"
                    ),
                ),
                (
                    "template_choice",
                    models.CharField(
                        choices=[
                            ("classic", "Classic"),
                            ("bold", "Bold"),
                            ("minimal", "Minimal"),
                        ],
                        default="classic",
                        max_length=30,
                    ),
                ),
                (
                    "registration_form_fields",
                    models.TextField(
                        blank=True,
                        help_text="Custom registration fields for this activity (one per line, use * for required)",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="event.event",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coordinator", "Coordinator"),
                            ("organizer", "Organizer"),
                            ("participant", "Participant"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "coordinator_role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("activity", "Activity Coordinator"),
                            ("event", "Event Coordinator"),
                            ("head", "Head Coordinator"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="activity",
            unique_together={("event", "name")},
        ),
        migrations.CreateModel(
            name="EventCoordinator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "user")},
            },
        ),
        migrations.CreateModel(
            name="EventCoordinatorInvite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("accepted", "Accepted")],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="event.event"
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_coordinator_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("event", "email"),
                        name="unique_pending_invite",
                    )
                ],
            },
        ),
    ]
