# Generated by Django 6.0.3 on 2026-03-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-date_of_event"]},
        ),
        migrations.AddField(
            model_name="event",
            name="image_url",
            field=models.CharField(
                blank=True, help_text="Event image URL", max_length=500
            ),
        ),
    ]
