# Generated by Django 5.2 on 2026-04-06 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0004_activitycoordinator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activity",
            options={"ordering": ["start_time"]},
        ),
        migrations.AddField(
            model_name="activity",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="max_participants",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="registration_fee",
            field=models.CharField(blank=True, default="Free", max_length=200),
        ),
        migrations.AlterField(
            model_name="activitycoordinator",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_coordinators",
                to="event.activity",
            ),
        ),
        migrations.AlterField(
            model_name="activityregistrationformfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("number", "Number"),
                    ("textarea", "Textarea"),
                    ("choice", "Choice"),
                    ("date", "Date"),
                    ("file", "File Upload"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration_form_fields",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="eventcoordinator",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coordinators",
                to="event.event",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityregistrationformfield",
            unique_together={("activity", "label")},
        ),
    ]
