# Generated by Django 5.2 on 2026-04-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0005_alter_activity_options_activity_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="eligibility",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="prize",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="activity",
            name="rules",
            field=models.TextField(blank=True),
        ),
    ]
