# Generated by Django 6.0.3 on 2026-04-07 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0006_activity_date_activity_eligibility_activity_prize_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("ongoing", "Ongoing"),
                    ("completed", "Completed"),
                ],
                default="upcoming",
                max_length=20,
            ),
        ),
    ]
