# Generated by Django 6.0.3 on 2026-04-10

from django.db import migrations, models
from django.db.models.functions import Lower
from django.utils.text import slugify


def forward_fill_event_names(apps, schema_editor):
    Event = apps.get_model("event", "Event")
    db_alias = schema_editor.connection.alias

    used_names = set()
    used_slugs = set()

    for event in Event.objects.using(db_alias).order_by("id"):
        base_name = (event.name or event.event or "").strip()
        if not base_name:
            base_name = f"Event {event.id}"

        candidate_name = base_name
        suffix = 2
        while candidate_name.casefold() in used_names:
            candidate_name = f"{base_name} ({suffix})"
            suffix += 1
        used_names.add(candidate_name.casefold())

        base_slug = slugify(candidate_name) or f"event-{event.id}"
        candidate_slug = base_slug
        slug_suffix = 2
        while candidate_slug in used_slugs:
            candidate_slug = f"{base_slug}-{slug_suffix}"
            slug_suffix += 1
        used_slugs.add(candidate_slug)

        event.name = candidate_name
        event.event = candidate_name
        event.slug = candidate_slug
        event.save(update_fields=["name", "event", "slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0007_event_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="name",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.RunPython(forward_fill_event_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(Lower("name"), name="unique_event_name_ci"),
        ),
    ]
