# Generated by Django 5.2 on 2026-04-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0008_event_name_slug_and_ci_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="form_schema",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="event",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
    ]
