# Generated by Django 5.2 on 2026-04-10 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_event_form_schema_event_is_draft"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.URLField(blank=True, help_text="Event website URL"),
        ),
    ]
