# Generated by Django 6.0.3 on 2026-04-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0009_remove_event_unique_event_name_ci_activity_organizer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a QR code image for the activity.",
                null=True,
                upload_to="activities/qr_codes/",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="banner_text",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="event",
            name="form_schema",
            field=models.TextField(blank=True, default="[]"),
        ),
        migrations.AddField(
            model_name="event",
            name="is_draft",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="event",
            name="qr_code_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a QR code image for the event.",
                null=True,
                upload_to="events/qr_codes/",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="website",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="activity",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="announcement",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="event",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="event",
            name="registration",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
