# Generated by Django 5.2 on 2026-04-13 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0010_activity_qr_code_image_event_banner_text_and_more"),
        ("event", "0010_event_website"),
    ]

    operations = []
